# Generated by Django 5.2.6 on 2025-09-27 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description_html', models.TextField(blank=True, default='')),
                ('domain', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=140)),
                ('school', models.CharField(blank=True, default='', max_length=64)),
                ('manual_html', models.TextField()),
                ('attributes_json', models.JSONField(blank=True, default=dict)),
                ('rune_effects_json', models.JSONField(blank=True, default=dict)),
                ('version', models.CharField(blank=True, default='1.0', max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
